packages:
  - apps/*
  - packages/*
  - supabase

onlyBuiltDependencies:
  - "@clerk/shared"
  - "@sentry/cli"
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - msgpackr-extract
  - sharp
  - tesseract.js
  - unrs-resolver
